config/routes.rb
Rails.application.routes.draw do
  resources :bills
  root to: 'page#home'
  get '/contact', to: 'page#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  has_many :products, dependent: :destroy
  accepts_nested_attributes_for :products, 
                                allow_destroy: true, 
                                reject_if: proc { |att| att['prodname'].blank? }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :bill, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: %i[ show edit update destroy ]

  # GET /bills or /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1 or /bills/1.json
  def show
    @products = Product.where(bill_id: @bill.id)
  end

  # GET /bills/new
  def new
    @bill = Bill.new
    @bill.products.build
  end

  # GET /bills/1/edit
  def edit
    products = @bill.products.build
  end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to bill_url(@bill), notice: "Bill was successfully created." }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bill_url(@bill), notice: "Bill was successfully updated." }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:custname, :billno, :billdt, products_attributes: Product.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Bills"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/bills/_form.html.erb
<%= simple_form_for(@bill) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :custname %>
    <%= f.input :billno %>
    <%= f.input :billdt %>
  </div>

  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th class="col-3">Product</th>
        <th class="col-2">Rate</th>
        <th class="col-1">Qty</th>
        <th class="col-2">Amount</th>
      </tr>
    </thead>
    <tbody class='products'>
      <%= f.simple_fields_for :products do |builder| %>
        <%= render 'product_fields', f: builder %>
      <% end %>
    </tbody>
  </table>

  <table class='table'>
    <tr>
      <td class="col-3" ></td>
      <td class="col-2" ></td>
      <td class="col-1" ></td>
      <td class="col-2" ></td>
      <td>Total</td>
    </tr>
  </table>

  <div class="form-actions">
    <%= link_to_add_association 'Add Product', f, :products, class: 'btn btn-primary', data: { association_insertion_node: '.products', association_insertion_method: :append } %>
    <%= f.button :submit %>
    
  </div>
<% end %>

app/views/bills/_product_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= link_to_remove_association "X", f, class: 'btn btn-danger btn-xs' %>
  </td>
  <td><%= f.input :prodname, label: false %></td>
  <td><%= f.input :qty, label: false%></td>
  
  
  <!-- td><input type="text" value="<%= @words %>" data-reflex="input->Sum#words"></td -->
  <td><%= f.input :rate, label: false %></td>
  <td></td>
  <td><%= @words %></td>
  <td></td>
</tr>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<table class = "table">
  <thead>
    <tr>
      <th class="col-3" >Custname</th>
      <th class="col-2" >Billno</th>
      <th class="col-2" >Billdt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.custname %></td>
        <td><%= bill.billno %></td>
        <td><%= bill.billdt %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Custname:</strong>
  <%= @bill.custname %>
</p>

<p>
  <strong>Billno:</strong>
  <%= @bill.billno %>
</p>

<p>
  <strong>Billdt:</strong>
  <%= @bill.billdt %>
</p>

<table class = "table">
  <thead>
    <tr>
      <th class="col-3" >Product Name</th>
      <th class="col-2" >Qty No.</th>
      <th class="col-2" >Rate Amt</th>
      <th class="col-2" > Amount </th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.prodname %></td>
        <td><%= product.qty %></td>
        <td><%= product.rate %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table class='table'>
    <tr>
      <td class="col-3" ></td>
      <td class="col-2" ></td>
      <td class="col-1" ></td>
      <td class="col-2" ></td>
      <td>Total</td>
    </tr>
  </table>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/layouts/_footer.html.erb
<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
    </div>
    
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container">
    <%= link_to "Bills", root_path, class: "navbar-brand" %>
    <ul class="nav justify-content-end" >
      <li><%= link_to "Home",  root_path, class:"nav-link"%></li>
      <li><%= link_to "Bills",  bills_path, class:"nav-link"%></li>
      <li><%= link_to "Contact",  contact_path, class:"nav-link"%></li>
      <%= csrf_meta_tags %>

    </ul>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body  class='bg-light'>
    <%= render 'layouts/header' %>
    <br/>
    <br/>
    <br/>
    <div class="container  pt-5 pb-5">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<% provide(:title, 'Home') %>
<h1>Home</h1>


<a href="#"
  data-reflex="click->Counter#increment"
  data-step="1" 
  data-count="<%= @count.to_i %>"
> Increment <%= @count.to_i %></a>

<br>

<form>
  <input type="text" data-reflex="input->Calc#sum" autofocus="true" placeholder="Type an integer"><br>
  times<br>
  <input type="text" name="multiplier" value="5">
</form>
<p>Result: <span id="result"></span></p>